PREFIX oio: <http://www.geneontology.org/formats/oboInOwl#>
PREFIX VFBd: <http://virtualflybrain.org/reports/>

CONSTRUCT { ?x <http://n2o.neo/property/nodeLabel> 'FlyEM-HB' . }
WHERE {
  ?x
  oio:hasDbXref
  VFBd:neuprint_JRC_Hemibrain_1point1 .
}
