PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

CONSTRUCT {
	?x <http://n2o.neo/property/nodeLabel> "has_subClass" .
}
WHERE {
  ?y owl:subClassOf ?x . 
}
