PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX OBI: <http://purl.obolibrary.org/obo/OBI_>
PREFIX FBcv: <http://purl.obolibrary.org/obo/FBcv_>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

CONSTRUCT { ?entity <http://n2o.neo/property/nodeLabel> 'scRNAseq' . }
WHERE {
  ?entity dcterms:source* ?dataset .
  ?dataset rdf:type ?b .
  ?b rdf:type owl:Restriction ;
           owl:onProperty OBI:0000312 ;
           owl:someValuesFrom ?assay .
  ?assay rdfs:subClassOf* FBcv:0009000 .
}
